name: ESLint

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - 'main'
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    test:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node v18
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Run ESLint
              run: npm run lint
